//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDamco.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTemplate
    {
        public int Id { get; set; }
        public string LoginCopiedFrom { get; set; }
        public int RoleCopiedFrom { get; set; }
        public int Role { get; set; }
        public string Description { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string CachedRoleName { get; set; }
        public int CachedOrganizationId { get; set; }
        public string CachedOrganizationName { get; set; }
    }
}
