//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDamco.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation
    {
        public int Id { get; set; }
        public string UId { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Target { get; set; }
        public string IECompatibilityMode { get; set; }
        public byte Priority { get; set; }
        public string UAMApplication { get; set; }
        public string UAMFunction { get; set; }
        public bool NewTab { get; set; }
    }
}
