//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDamco.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetInstanceHistory
    {
        public int WidgetInstance_Id { get; set; }
        public string Login { get; set; }
        public int Role { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public int Widget_Id { get; set; }
    
        public virtual Widget Widget { get; set; }
    }
}
