//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDamco.Reporting {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://more.apmoller.net/reporting", ConfigurationName="Reporting.ReportingWebServicesSoapBinding")]
    public interface ReportingWebServicesSoapBinding {
        
        // CODEGEN: Generating message contract since element name CacheKey from namespace http://more.apmoller.net/reporting is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        myDamco.Reporting.GetRecentSearchesResponse GetRecentSearches(myDamco.Reporting.GetRecentSearchesRequest request);
        
        // CODEGEN: Generating message contract since element name CacheKey from namespace http://more.apmoller.net/reporting is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        myDamco.Reporting.GetRecentReportsResponse GetRecentReports(myDamco.Reporting.GetRecentReportsRequest request);
        
        // CODEGEN: Generating message contract since element name CacheKey from namespace http://more.apmoller.net/reporting is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        myDamco.Reporting.GetScheduleReportsResponse GetScheduleReports(myDamco.Reporting.GetScheduleReportsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecentSearchesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecentSearches", Namespace="http://more.apmoller.net/reporting", Order=0)]
        public myDamco.Reporting.GetRecentSearchesRequestBody Body;
        
        public GetRecentSearchesRequest() {
        }
        
        public GetRecentSearchesRequest(myDamco.Reporting.GetRecentSearchesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://more.apmoller.net/reporting")]
    public partial class GetRecentSearchesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CacheKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int RoleId;
        
        public GetRecentSearchesRequestBody() {
        }
        
        public GetRecentSearchesRequestBody(string CacheKey, string UserLogin, int RoleId) {
            this.CacheKey = CacheKey;
            this.UserLogin = UserLogin;
            this.RoleId = RoleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecentSearchesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecentSearchesResponse", Namespace="http://more.apmoller.net/reporting", Order=0)]
        public myDamco.Reporting.GetRecentSearchesResponseBody Body;
        
        public GetRecentSearchesResponse() {
        }
        
        public GetRecentSearchesResponse(myDamco.Reporting.GetRecentSearchesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://more.apmoller.net/reporting")]
    public partial class GetRecentSearchesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WidgetResponse;
        
        public GetRecentSearchesResponseBody() {
        }
        
        public GetRecentSearchesResponseBody(string WidgetResponse) {
            this.WidgetResponse = WidgetResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecentReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecentReports", Namespace="http://more.apmoller.net/reporting", Order=0)]
        public myDamco.Reporting.GetRecentReportsRequestBody Body;
        
        public GetRecentReportsRequest() {
        }
        
        public GetRecentReportsRequest(myDamco.Reporting.GetRecentReportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://more.apmoller.net/reporting")]
    public partial class GetRecentReportsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CacheKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserLogin;
        
        public GetRecentReportsRequestBody() {
        }
        
        public GetRecentReportsRequestBody(string CacheKey, string UserLogin) {
            this.CacheKey = CacheKey;
            this.UserLogin = UserLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecentReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecentReportsResponse", Namespace="http://more.apmoller.net/reporting", Order=0)]
        public myDamco.Reporting.GetRecentReportsResponseBody Body;
        
        public GetRecentReportsResponse() {
        }
        
        public GetRecentReportsResponse(myDamco.Reporting.GetRecentReportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://more.apmoller.net/reporting")]
    public partial class GetRecentReportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WidgetResponse;
        
        public GetRecentReportsResponseBody() {
        }
        
        public GetRecentReportsResponseBody(string WidgetResponse) {
            this.WidgetResponse = WidgetResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetScheduleReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetScheduleReports", Namespace="http://more.apmoller.net/reporting", Order=0)]
        public myDamco.Reporting.GetScheduleReportsRequestBody Body;
        
        public GetScheduleReportsRequest() {
        }
        
        public GetScheduleReportsRequest(myDamco.Reporting.GetScheduleReportsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://more.apmoller.net/reporting")]
    public partial class GetScheduleReportsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CacheKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserLogin;
        
        public GetScheduleReportsRequestBody() {
        }
        
        public GetScheduleReportsRequestBody(string CacheKey, string UserLogin) {
            this.CacheKey = CacheKey;
            this.UserLogin = UserLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetScheduleReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetScheduleReportsResponse", Namespace="http://more.apmoller.net/reporting", Order=0)]
        public myDamco.Reporting.GetScheduleReportsResponseBody Body;
        
        public GetScheduleReportsResponse() {
        }
        
        public GetScheduleReportsResponse(myDamco.Reporting.GetScheduleReportsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://more.apmoller.net/reporting")]
    public partial class GetScheduleReportsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WidgetResponse;
        
        public GetScheduleReportsResponseBody() {
        }
        
        public GetScheduleReportsResponseBody(string WidgetResponse) {
            this.WidgetResponse = WidgetResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportingWebServicesSoapBindingChannel : myDamco.Reporting.ReportingWebServicesSoapBinding, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportingWebServicesSoapBindingClient : System.ServiceModel.ClientBase<myDamco.Reporting.ReportingWebServicesSoapBinding>, myDamco.Reporting.ReportingWebServicesSoapBinding {
        
        public ReportingWebServicesSoapBindingClient() {
        }
        
        public ReportingWebServicesSoapBindingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportingWebServicesSoapBindingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingWebServicesSoapBindingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingWebServicesSoapBindingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myDamco.Reporting.GetRecentSearchesResponse myDamco.Reporting.ReportingWebServicesSoapBinding.GetRecentSearches(myDamco.Reporting.GetRecentSearchesRequest request) {
            return base.Channel.GetRecentSearches(request);
        }
        
        public string GetRecentSearches(string CacheKey, string UserLogin, int RoleId) {
            myDamco.Reporting.GetRecentSearchesRequest inValue = new myDamco.Reporting.GetRecentSearchesRequest();
            inValue.Body = new myDamco.Reporting.GetRecentSearchesRequestBody();
            inValue.Body.CacheKey = CacheKey;
            inValue.Body.UserLogin = UserLogin;
            inValue.Body.RoleId = RoleId;
            myDamco.Reporting.GetRecentSearchesResponse retVal = ((myDamco.Reporting.ReportingWebServicesSoapBinding)(this)).GetRecentSearches(inValue);
            return retVal.Body.WidgetResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myDamco.Reporting.GetRecentReportsResponse myDamco.Reporting.ReportingWebServicesSoapBinding.GetRecentReports(myDamco.Reporting.GetRecentReportsRequest request) {
            return base.Channel.GetRecentReports(request);
        }
        
        public string GetRecentReports(string CacheKey, string UserLogin) {
            myDamco.Reporting.GetRecentReportsRequest inValue = new myDamco.Reporting.GetRecentReportsRequest();
            inValue.Body = new myDamco.Reporting.GetRecentReportsRequestBody();
            inValue.Body.CacheKey = CacheKey;
            inValue.Body.UserLogin = UserLogin;
            myDamco.Reporting.GetRecentReportsResponse retVal = ((myDamco.Reporting.ReportingWebServicesSoapBinding)(this)).GetRecentReports(inValue);
            return retVal.Body.WidgetResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myDamco.Reporting.GetScheduleReportsResponse myDamco.Reporting.ReportingWebServicesSoapBinding.GetScheduleReports(myDamco.Reporting.GetScheduleReportsRequest request) {
            return base.Channel.GetScheduleReports(request);
        }
        
        public string GetScheduleReports(string CacheKey, string UserLogin) {
            myDamco.Reporting.GetScheduleReportsRequest inValue = new myDamco.Reporting.GetScheduleReportsRequest();
            inValue.Body = new myDamco.Reporting.GetScheduleReportsRequestBody();
            inValue.Body.CacheKey = CacheKey;
            inValue.Body.UserLogin = UserLogin;
            myDamco.Reporting.GetScheduleReportsResponse retVal = ((myDamco.Reporting.ReportingWebServicesSoapBinding)(this)).GetScheduleReports(inValue);
            return retVal.Body.WidgetResponse;
        }
    }
}
