//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDamco.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCategory
    {
        public NewsCategory()
        {
            this.NewsItem = new HashSet<NewsItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public string Description { get; set; }
        public bool Downtime { get; set; }
        public string editUAMApplication { get; set; }
        public string editUAMFunction { get; set; }
        public string showUAMApplication { get; set; }
        public string showUAMFunction { get; set; }
        public string Configuration { get; set; }
    
        public virtual ICollection<NewsItem> NewsItem { get; set; }
    }
}
