//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDamco.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public Widget()
        {
            this.WidgetInstance = new HashSet<WidgetInstance>();
            this.WidgetInstanceHistory = new HashSet<WidgetInstanceHistory>();
        }
    
        public int Id { get; set; }
        public string UId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string Icon { get; set; }
        public string Template { get; set; }
        public string TemplateHTML { get; set; }
        public string TemplateInstanceHTML { get; set; }
        public string TemplateCSS { get; set; }
        public string TemplateJS { get; set; }
        public string Configuration { get; set; }
        public string ServiceConfiguration { get; set; }
        public string ConfigurationSchema { get; set; }
        public string ServiceConfigurationSchema { get; set; }
        public string InstanceConfigurationSchema { get; set; }
        public bool Editable { get; set; }
        public bool Disabled { get; set; }
        public string UAMApplication { get; set; }
        public string UAMFunction { get; set; }
        public string ServiceURL { get; set; }
    
        public virtual ICollection<WidgetInstance> WidgetInstance { get; set; }
        public virtual ICollection<WidgetInstanceHistory> WidgetInstanceHistory { get; set; }
    }
}
